package student_project;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Admin_Window_2 extends javax.swing.JFrame {
Date date;
    /**
     * Creates new form Admin_Window_4
     */
    public Admin_Window_2() {
        initComponents();
        
         
       

    }

    Admin_Window_2(Date date) {
         initComponents();
        this.date=date;
                jDateChooser1.getJCalendar().setMinSelectableDate(new java.util.Date());

        jLabel1.setBackground (new Color(0,0,0,64));
        
          jLabel2.setBackground (new Color(0,0,0,64));
                  
          jLabel3.setBackground (new Color(0,0,0,64));
                  
          jLabel4.setBackground (new Color(0,0,0,64));
          


           
          jComboBox2.setBackground (new Color(0,0,0,64));
          
          jComboBox3.setBackground (new Color(0,0,0,64));
  
                                   jDateChooser1.setBackground (new Color(0,0,0,64));
                                                      jPanel1.setBackground (new Color(0,0,0,64));
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {

                ImageIcon im=new ImageIcon("Admin_Windows_Image.jpg");
                Image i=im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }
        }
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complaint ID", "Description", "Worker type", "Name", "Block", "Room no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Select Complaint");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("    Assign Deadline");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText(" Select Worker Type");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("    Assign Worker");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "plumber", "carpenter", "electrician" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_project/Go_back_Image.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("Show Me The Complaints");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("Assign Complaint");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton3)
                        .addGap(81, 81, 81)
                        .addComponent(jButton2)))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Admin_Window_1 obj = new Admin_Window_1();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  SimpleDateFormat ft = 
      new SimpleDateFormat ("yyyy-MM-dd");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
 try
 {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
    
    Statement st=conn.createStatement();
    String query=" select complaint_info.comp_id,complaint_info.complaint,complaint_info.worker_type,student_info.name,student_info.block,student_info.room_no from complaint_info inner join student_info on student_info.prn = complaint_info.prn and status = 0 and complaint_info.comp_date='" + ft.format(date) + "' ";
    ResultSet rs = st.executeQuery(query);
    
    while (rs.next())
    {
        String d1=rs.getString("comp_id");
        String d2=rs.getString("complaint");
        String d3=rs.getString("worker_type");
        String d4=rs.getString("name");
        String d5=rs.getString("block");
        String d6=rs.getString("room_no");
        
        model.addRow(new Object[]{d1,d2,d3,d4,d5,d6});
    }
    rs.close();
    st.close();
    conn.close();
 }
 catch (ClassNotFoundException | SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity"); 
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
 if(jComboBox2.getSelectedItem()=="plumber")
 {
        try
 {
     
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
     String query="select * from worker_id where worker_type='plumber';" ;
    PreparedStatement st=conn.prepareStatement(query); 
    ResultSet rs = st.executeQuery(query);
    jComboBox3.removeAllItems();
   while(rs.next())
   {
       String name=rs.getString("worker_name");
       jComboBox3.addItem(name);
   }
    rs.close();
    st.close();
    conn.close();
 }
 catch (ClassNotFoundException|SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity "); 
 }
 }
       else if(jComboBox2.getSelectedItem()=="carpenter")
 {
        try
 {
     
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
     String query="select * from worker_id where worker_type='carpenter';" ;
    PreparedStatement st=conn.prepareStatement(query); 
    ResultSet rs = st.executeQuery(query);
     jComboBox3.removeAllItems();
   while(rs.next())
   {
       String name=rs.getString("worker_name");
       jComboBox3.addItem(name);
   }
    rs.close();
    st.close();
    conn.close();
 }
 catch (ClassNotFoundException|SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity"); 
 }
 }
       else if(jComboBox2.getSelectedItem()=="electrician")
 {
        try
 {
     
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
     String query="select * from worker_id where worker_type='electrician';" ;
    PreparedStatement st=conn.prepareStatement(query); 
    ResultSet rs = st.executeQuery(query);
     jComboBox3.removeAllItems();
   while(rs.next())
   {
       String name=rs.getString("worker_name");
       jComboBox3.addItem(name);
   }
    rs.close();
    st.close();
    conn.close();
 }
 catch (ClassNotFoundException|SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity2442"); 
 }
 }
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try
 {
     String name = jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
     
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
    Statement st=conn.createStatement(); 
    //JOptionPane.showMessageDialog(this,"asdf");
     String query="select * from worker_id where worker_name='" +name+ "' " ;
    ResultSet rs = st.executeQuery(query);
   // JOptionPane.showMessageDialog(this,"qwerty");
    rs.next();
    //JOptionPane.showMessageDialog(this,"dfd");
     String workerid = rs.getString("worker_id");
    rs.close();
    st.close();
    conn.close();
     try
 {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn1=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
    
    String query1="update complaint_info set worker_id ='" +workerid+ "' where comp_id='" +jTextField1.getText()+ "'";
    PreparedStatement pst =conn1.prepareStatement(query1);

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null,"inserted sucessfully"); 
 }
catch (ClassNotFoundException | SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivityinn"); 
 }      
 }
     catch (ClassNotFoundException|SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivityoou"); 
 }
         try
 {
     Date date1=jDateChooser1.getDate();
      SimpleDateFormat ft = 
      new SimpleDateFormat ("yyyy-MM-dd");
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
    JOptionPane.showMessageDialog(this,ft.format(date1));
    String query="update complaint_info set free_date ='" +ft.format(date1)+ "' where comp_id='" +jTextField1.getText()+ "'";
    PreparedStatement pst =conn.prepareStatement(query);
    pst.executeUpdate();
    JOptionPane.showMessageDialog(null,"inserted sucessfully"); 
 }
catch (ClassNotFoundException | SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity"); 
 }
         try
 {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn1=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/test0","root","root");
    
    String query2="update complaint_info set status ='50' where comp_id='" +jTextField1.getText()+ "'";
    PreparedStatement pst2 =conn1.prepareStatement(query2);

    pst2.executeUpdate();
    JOptionPane.showMessageDialog(null,"inserted sucessfully"); 
 }
catch (ClassNotFoundException | SQLException e)
 {
     JOptionPane.showMessageDialog(null,"error in connectivity"); 
 } 
  
    
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Window_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Window_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Window_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Window_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Window_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   
}
